### ISSUE TITLE
Prevent browsers from re-downloading the same static files repeatedly

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/ansible-role-tinypilot#144]
Splitting off from https://github.com/tiny-pilot/tinypilot/issues/538#issuecomment-881484720

TinyPilot's nginx configuration [disables caching](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/c565b6020c419db31d3fb94c86f5cf019c56908c/tasks/nginx.yml#L62) for static resources. I originally did this because it put the app into an inconsistent state after the user applied updates (e.g., they'd reload after an update and have different versions of various static files). But we realized that it has the unintended consequence of forcing the browser to redownload the same file dozens of times for a single page load on Chrome (and possibly other browsers).

We should revise the cache policy so that updates don't throw the frontend into an inconsistent state but we're also not causing bizarre browser behavior of redownloading the same file.

**Comment by jotaen** [comment]
Unfortunately, behaviour is wildly inconsistent across browsers, so this issue requires the following fixes. All in all, I’ve tested Firefox and Chrome, on Windows 10, Linux and MacOS. (I’ve also tested MS Edge on Win10, but that’s Chromium-based nowadays, so it behaves the same as Chrome anyway.)

## Part 1: Repeated CSS (Chrome)
This is the biggest issue and it’s happening on Chrome (both Win and MacOS).

Chrome issues one request per `@import` statement (in the CSS) encountered. In our web components, there is no way around importing the CSS individually, since the shadow DOM’s CSS doesn’t inherit from the global scope. That’s why we can’t globally import the CSS upfront. The easiest solution is to turn on caching, as proposed in https://github.com/tiny-pilot/ansible-role-tinypilot/pull/145

I’ve also looked into other ways that don’t rely on heuristics, but that would result in more complexity:

- The most common solution is to put a version number either into the file name itself, or into the query string, and then allow indefinite caching per file version. The biggest problem here is how to embedd these version numbers into the HTML. For that we’d actually need bundling first, then we could come back to this approach.
- As an alternative, we could rely on `ETag` or `If-Modified-Since` headers, which nginx would give us for free. That would still make the browser trigger the requests, though, even if there is no data transmitted in the end because the server sends back a `304 Not Modified`.

## Part 2: Repeated JS (Firefox on MacOS)
This is currently a minor issue and I can only see it on Firefox on MacOS.

Firefox on MacOS (as opposed to Firefox on Windows, or Chrome) issues one request per `<script src="">` statement (in the HTML). It’s not doing this for JS modules (like `import { something } from 'foo.js';`), only for the script-tags, and unfortunately it’s persistently ignoring the cache headers for some reason. As opposed to CSS, all JS is global, even within the web components, so it’s just fine to dump the JS into the global scope right from the start: https://github.com/tiny-pilot/tinypilot/pull/747
